local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

-- matter-plant

data:extend({
    {
        type = "item",
        name = "simulacrum-computer-4",
        icon = "__simulacrum__/graphics/icons/simulacrum-computer-4.png",
        icon_size = 128, icon_mipmaps = 4,
        subgroup = "simulacrum-computers",
        order = "ae",
        stack_size = 1,
        place_result = "simulacrum-computer-4"
    },
    {
    type = "furnace",
    name = "simulacrum-computer-4",
    icon = "__simulacrum__/graphics/icons/simulacrum-computer-4.png",
    icon_size = 128,
    icon_mipmaps = 4,
    flags = {
      "placeable-player",
      "placeable-neutral",
      "player-creation",
      "not-blueprintable",
      "no-copy-paste",
      "not-upgradable",
      },
    minable = { mining_time = 1, result = "simulacrum-computer-4" },
    max_health = 2000,
    damaged_trigger_effect = hit_effects.entity(),
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    resistances = {
      { type = "physical", percent = 60 },
      { type = "fire", percent = 70 },
      { type = "impact", percent = 70 },
    },
    collision_box = { { -3.25, -3.25 }, { 3.25, 3.25 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    fast_replaceable_group = "assembling-machine",
    animation = {
      layers = {
        {
          filename = "__simulacrum__/graphics/entity/computer-4/matter-plant.png",
          priority = "high",
          scale = scale,
          width = 231,
          height = 250,
          frame_count = 1,
          shift = { -0.1, -0.2 },
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-4/hr-matter-plant.png",
            priority = "high",
            width = 462,
            height = 500,
            frame_count = 1,
            shift = { -0.1, -0.2 },
            scale = 0.5,
          },
        },
        {
          filename = "__simulacrum__/graphics/entity/computer-4/matter-plant-sh.png",
          priority = "high",
          scale = scale,
          width = 252,
          height = 222,
          frame_count = 1,
          draw_as_shadow = true,
          shift = { 0.23, 0.24 },
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-4/hr-matter-plant-sh.png",
            priority = "high",
            width = 504,
            height = 444,
            frame_count = 1,
            draw_as_shadow = true,
            shift = { 0.23, 0.24 },
            scale = 0.5,
          },
        },
      },
    },
    working_visualisations = {
      {
        draw_as_light = true,
        blend_mode = "additive-soft",
        animation = {
          filename = "__simulacrum__/graphics/entity/computer-4/matter-plant-working-light.png",
          priority = "high",
          scale = scale,
          width = 231,
          height = 250,
          frame_count = 30,
          line_length = 6,
          shift = { -0.1, -0.2 },
          animation_speed = 0.75,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-4/hr-matter-plant-working-light.png",
            priority = "high",
            width = 462,
            height = 500,
            frame_count = 30,
            line_length = 6,
            shift = { -0.1, -0.2 },
            scale = 0.5,
            animation_speed = 0.75,
          },
        },
      },
      {
        draw_as_glow = true,
        blend_mode = "additive-soft",
        synced_fadeout = true,
        animation = {
          filename = "__simulacrum__/graphics/entity/computer-4/matter-plant-working-glow.png",
          priority = "high",
          scale = scale,
          width = 231,
          height = 250,
          frame_count = 30,
          line_length = 6,
          shift = { -0.1, -0.2 },
          animation_speed = 0.75,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-4/hr-matter-plant-working-glow.png",
            priority = "high",
            width = 462,
            height = 500,
            frame_count = 30,
            line_length = 6,
            shift = { -0.1, -0.2 },
            scale = 0.5,
            animation_speed = 0.75,
          },
        },
      },
      {
        animation = {
          filename = "__simulacrum__/graphics/entity/computer-4/matter-plant-working.png",
          scale = scale,
          width = 231,
          height = 250,
          frame_count = 30,
          line_length = 6,
          shift = { -0.1, -0.2 },
          animation_speed = 0.75,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-4/hr-matter-plant-working.png",
            width = 462,
            height = 500,
            frame_count = 30,
            line_length = 6,
            shift = { -0.1, -0.2 },
            scale = 0.5,
            animation_speed = 0.75,
          },
        },
      },
    },
    crafting_categories = {"harddrives-consume-none"},
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = {
      sound = { filename = "__simulacrum__/graphics/entity/computer-4/matter-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg" },
      apparent_volume = 1.5,
    },
    energy_usage = "5MW",
    allowed_effects = {"pollution"},
    result_inventory_size = 1,
    source_inventory_size = 1,
    energy_source =
    {
    type = "electric",
    usage_priority = "secondary-input",
    emissions_per_minute = 5,
    drain = "500kW",
    buffer_capacity = "20J"   
    },
    return_ingredients_on_change = false,
    module_specification = { module_slots = 5 },
    open_sound = { filename = "__simulacrum__/graphics/entity/open.ogg", volume = 1 },
    close_sound = { filename = "__simulacrum__/graphics/entity/close.ogg", volume = 0.85 },
    crafting_speed = 1,
  },
})
