local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

-- quantum-computer

data:extend({
    {
        type = "item",
        name = "simulacrum-computer-3",
        icon = "__simulacrum__/graphics/icons/simulacrum-computer-3.png",
        icon_size = 64, icon_mipmaps = 4,
        subgroup = "simulacrum-computers",
        order = "ad",
        stack_size = 16,
        place_result = "simulacrum-computer-3"
    },
  {
    type = "furnace",
    name = "simulacrum-computer-3",
    icon = "__simulacrum__/graphics/icons/simulacrum-computer-3.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = {
      "placeable-player",
      "placeable-neutral",
      "player-creation",
      "not-blueprintable",
      "no-copy-paste",
      "not-upgradable",
      },
    minable = { mining_time = 1, result = "simulacrum-computer-3" },
    damaged_trigger_effect = hit_effects.entity(),
    max_health = 1000,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    resistances = {
      { type = "physical", percent = 50 },
      { type = "fire", percent = 70 },
      { type = "impact", percent = 70 },
    },
    collision_box = { { -2.8, -2.8 }, { 2.8, 2.8 } },
    selection_box = { { -2.95, -2.95 }, { 2.95, 2.95 } },
    fast_replaceable_group = "assembling-machine",
    animation = {
      layers = {
        {
          filename = "__simulacrum__/graphics/entity/computer-3/quantum-computer.png",
          priority = "high",
          width = 200,
          height = 210,
          shift = { 0, -0.2 },
          frame_count = 48,
          line_length = 8,
          animation_speed = 0.25,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-3/hr-quantum-computer.png",
            priority = "high",
            width = 400,
            height = 420,
            shift = { 0, -0.2 },
            frame_count = 48,
            line_length = 8,
            animation_speed = 0.25,
            scale = 0.5,
          },
        },
        {
          filename = "__simulacrum__/graphics/entity/computer-3/quantum-computer-sh.png",
          priority = "medium",
          width = 201,
          height = 181,
          shift = { 0.19, 0.315 },
          frame_count = 1,
          repeat_count = 48,
          draw_as_shadow = true,
          animation_speed = 0.25,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-3/hr-quantum-computer-sh.png",
            priority = "medium",
            width = 402,
            height = 362,
            shift = { 0.19, 0.315 },
            frame_count = 1,
            repeat_count = 48,
            draw_as_shadow = true,
            animation_speed = 0.25,
            scale = 0.5,
          },
        },
      },
    },
    crafting_speed = 1,
    working_visualisations = {
      {
        draw_as_light = true,
        animation = {
          filename = "__simulacrum__/graphics/entity/computer-3/quantum-computer-light.png",
          priority = "extra-high",
          width = 200,
          height = 210,
          shift = { 0, -0.2 },
          frame_count = 48,
          line_length = 8,
          animation_speed = 0.25,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-3/hr-quantum-computer-light.png",
            priority = "extra-high",
            width = 400,
            height = 420,
            shift = { 0, -0.2 },
            frame_count = 48,
            line_length = 8,
            animation_speed = 0.25,
            scale = 0.5,
          },
        },
      },
      {
        draw_as_glow = true,
        blend_mode = "additive-soft",
        animation = {
          filename = "__simulacrum__/graphics/entity/computer-3/quantum-computer-glow.png",
          priority = "extra-high",
          width = 200,
          height = 210,
          shift = { 0, -0.2 },
          frame_count = 48,
          line_length = 8,
          animation_speed = 0.25,
          hr_version = {
            filename = "__simulacrum__/graphics/entity/computer-3/hr-quantum-computer-glow.png",
            priority = "extra-high",
            width = 400,
            height = 420,
            shift = { 0, -0.2 },
            frame_count = 48,
            line_length = 8,
            animation_speed = 0.25,
            scale = 0.5,
          },
        },
      },
      {
        light = {
          intensity = 0.85,
          size = 5,
          shift = { 0.0, 0.0 },
          color = { r = 0.35, g = 0.75, b = 1 },
        },
      },
    },
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = {
      sound = {
        filename = "__simulacrum__/graphics/entity/computer-3/quantum-computer.ogg",
        volume = 1.25,
      },
      idle_sound = { filename = "__base__/sound/idle1.ogg" },
      apparent_volume = 1.5,
    },
    energy_usage = "3MW",
    allowed_effects = {"pollution"},
    crafting_categories = {"harddrives-consume"},
    result_inventory_size = 1,
    source_inventory_size = 1,
    energy_source =
    {
    type = "electric",
    usage_priority = "secondary-input",
    emissions_per_minute = 4,
    drain = "100kW"   
    },
    return_ingredients_on_change = false,
    module_specification = { module_slots = 3 },
    open_sound = { filename = "__simulacrum__/graphics/entity/open.ogg", volume = 1 },
    close_sound = { filename = "__simulacrum__/graphics/entity/close.ogg", volume = 0.85 },
  },
})
