local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")

-- stabilizer-charging-station

data:extend({
    {
        type = "item",
        name = "one-time-pad",
        icon = "__simulacrum__/graphics/icons/one-time-pad.png",
        icon_size = 128, icon_mipmaps = 4,
        subgroup = "simulacrum-computers",
        order = "aa",
        stack_size = 32,
        place_result = "one-time-pad"
    },
    {
        type = "furnace",
        name = "one-time-pad",
        icon = "__simulacrum__/graphics/icons/one-time-pad.png",
        icon_size = 128,
        icon_mipmaps = 4,
        flags = {
            "placeable-player",
            "placeable-neutral",
            "player-creation",
            "not-blueprintable",
            "no-copy-paste",
            "not-upgradable",
            },
        minable = { mining_time = 1, result = "one-time-pad" },
        max_health = 500,
        damaged_trigger_effect = hit_effects.entity(),
        dying_explosion = "accumulator-explosion",
        corpse = "medium-remnants",
        resistances = {
        { type = "physical", percent = 20 },
        { type = "fire", percent = 35 },
        },
        collision_box = { { -0.7, -0.7 }, { 0.7, 0.7 } },
        selection_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
        animation = {
        layers = {
            {
            filename = "__simulacrum__/graphics/entity/one-time-pad/stabilizer-charging-station.png",
            priority = "high",
            width = 85,
            height = 85,
            frame_count = 80,
            line_length = 10,
            animation_speed = 0.4,
            scale = 0.8,
            hr_version = {
                filename = "__simulacrum__/graphics/entity/one-time-pad/hr-stabilizer-charging-station.png",
                priority = "high",
                width = 170,
                height = 170,
                frame_count = 80,
                line_length = 10,
                animation_speed = 0.4,
                scale = 0.4,
            },
            },
            {
            filename = "__simulacrum__/graphics/entity/one-time-pad/stabilizer-charging-station-sh.png",
            priority = "high",
            width = 85,
            height = 72,
            frame_count = 80,
            line_length = 8,
            animation_speed = 0.4,
            shift = { 0.23, 0.262 },
            draw_as_shadow = true,
            scale = 0.9,
            hr_version = {
                filename = "__simulacrum__/graphics/entity/one-time-pad/hr-stabilizer-charging-station-sh.png",
                priority = "high",
                width = 170,
                height = 144,
                frame_count = 80,
                line_length = 8,
                animation_speed = 0.4,
                shift = { 0.23, 0.262 },
                draw_as_shadow = true,
                scale = 0.4,
            },
            },
            {
                filename = "__simulacrum__/graphics/entity/one-time-pad/stabilizer-charging-station-light.png",
                priority = "high",
                width = 85,
                height = 85,
                frame_count = 80,
                line_length = 10,
                animation_speed = 0.4,
                scale = 0.8,
                draw_as_light = true,
                hr_version = {
                    filename = "__simulacrum__/graphics/entity/one-time-pad/hr-stabilizer-charging-station-light.png",
                    priority = "high",
                    width = 170,
                    height = 170,
                    frame_count = 80,
                    line_length = 10,
                    animation_speed = 0.4,
                    scale = 0.4,
                    draw_as_light = true,
                },
                },
        },
        },
        vehicle_impact_sound = sounds.generic_impact,
        working_sound = {
        sound = {
            filename = "__simulacrum__/graphics/entity/one-time-pad/stabilizer-charging-station.ogg",
            volume = 0.75,
        },
        idle_sound = {
            filename = "__base__/sound/idle1.ogg",
        },
        apparent_volume = 1.5,
        },
        water_reflection = {
        pictures = {
            filename = "__simulacrum__/graphics/entity/one-time-pad/stabilizer-charging-station-reflection.png",
            priority = "extra-high",
            width = 20,
            height = 25,
            shift = util.by_pixel(0, 40),
            variation_count = 1,
            scale = 5,
        },
        rotate = false,
        orientation_to_variation = false,
        },
        open_sound = sounds.machine_open,
        close_sound = sounds.machine_close,
        allowed_effects = {"pollution"},
        crafting_categories = {"harddrives-consume-none"},
        result_inventory_size = 1,
        crafting_speed = 1,
        energy_usage = "1MW",
        source_inventory_size = 1,
        energy_source =
        {
        type = "electric",
        usage_priority = "secondary-input",
        emissions_per_minute = 1,
        drain = "100kW",
        buffer_capacity = "20J"
        },
        return_ingredients_on_change = false,
        show_recipe_icon = false,

    },
})
